# Generated by Django 4.2.1 on 2023-06-20 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message', models.TextField(blank=True, null=True)),
                ('last_sender', models.CharField(blank=True, choices=[('me', 'Me'), ('customer', 'Customer')], max_length=255, null=True)),
                ('last_message_time', models.DateTimeField(blank=True, null=True)),
                ('last_read_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_read', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.contact')),
            ],
            options={
                'ordering': ['-last_message_time'],
            },
        ),
        migrations.CreateModel(
            name='TwilioAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twilio_account_sid', models.CharField(max_length=255)),
                ('twilio_auth_token', models.CharField(max_length=255)),
                ('websocket_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('me', 'Me'), ('customer', 'Customer')], max_length=255)),
                ('sms_sid', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField()),
                ('status', models.CharField(blank=True, choices=[('sent', 'Sent'), ('received', 'Received'), ('delivered', 'Delivered'), ('read', 'Read')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.conversation')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='twilio_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.twilioaccount'),
        ),
        migrations.AddField(
            model_name='contact',
            name='twilio_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.twilioaccount'),
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('is_default', models.BooleanField(default=False)),
                ('twilio_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.twilioaccount')),
            ],
            options={
                'unique_together': {('twilio_account', 'phone_number')},
            },
        ),
    ]
