# Generated by Django 4.2.1 on 2023-06-21 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='twilio_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='portal.twilioaccount'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='portal.contact'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='twilio_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='portal.twilioaccount'),
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='portal.conversation'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='twilio_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='portal.twilioaccount'),
        ),
        migrations.AlterField(
            model_name='twilioaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='twilio_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
