# Generated by Django 4.2.1 on 2023-06-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_contact_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='from_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='to_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(blank=True, choices=[('queued', 'Queued'), ('failed', 'Failed'), ('delivered', 'Delivered'), ('sent', 'Sent'), ('undelivered', 'Undelivered')], max_length=20, null=True),
        ),
    ]
