# Generated by Django 4.2.1 on 2023-07-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_message_from_number_message_to_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['is_read', '-last_message_time']},
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_lead',
            field=models.BooleanField(default=False),
        ),
    ]
