# Generated by Django 4.2.1 on 2023-07-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_conversation_options_conversation_is_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_received', models.FileField(null=True, upload_to='audio/custom_settings/')),
                ('got_a_lead', models.FileField(blank=True, null=True, upload_to='audio/custom_settings/')),
                ('message_delivered', models.FileField(blank=True, null=True, upload_to='audio/custom_settings/')),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
    ]
