# Generated by Django 4.2.1 on 2023-07-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_notificationsound_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsound',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
