# Generated by Django 4.2.1 on 2023-07-04 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_notificationsound_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotificationSound',
            new_name='SoundProfile',
        ),
    ]
