# Generated by Django 4.2.1 on 2023-07-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_rename_notificationsound_soundprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-last_message_time']},
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
    ]
