# Generated by Django 4.2.1 on 2023-07-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_alter_conversation_options_conversation_is_replied'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
