# Generated by Django 4.2.1 on 2023-07-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_alter_conversation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
