# Generated by Django 4.2.1 on 2023-07-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_alter_message_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='media',
            field=models.CharField(default='[]', max_length=1000),
        ),
    ]
