# Generated by Django 4.2.1 on 2024-09-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_alter_message_media'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='phonenumber',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='phonenumber',
            constraint=models.UniqueConstraint(fields=('twilio_account', 'phone_number'), name='unique_phone_per_account'),
        ),
        migrations.AddConstraint(
            model_name='phonenumber',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('phone_number',), name='unique_default_phone'),
        ),
    ]
