# Generated by Django 4.2.1 on 2024-11-29 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0016_alter_phonenumber_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twilioaccount',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twilio_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
